import React from 'react';
import { AnalysisResult } from '../services/aiService';

interface SevenDayPlanScreenProps {
    handle: string;
    result: AnalysisResult | null;
    onReset: () => void;
}

export const SevenDayPlanScreen: React.FC<SevenDayPlanScreenProps> = ({ handle, result, onReset }) => {
    // In a real scenario, this plan would be generated by AI based on the specific diagnosis.
    // For now, we use a static "Brutal Plan" template that fits the "Doug" persona.

    const planDays = [
        { day: 1, title: "O EXPURGO", task: "Arquive os últimos 9 posts que não servem para 'Posicionamento'. Se não vende e não constrói autoridade, é lixo. Limpe a casa." },
        { day: 2, title: "A NOVA BIO", task: "Reescreva sua bio. Linha 1: O que você faz. Linha 2: Para quem (seja específico, exclua curiosos). Linha 3: O que eu ganho clicando no link. Sem emojis fofos." },
        { day: 3, title: "PROVA SOCIAL AGRESSIVA", task: "Poste um print de resultado ou feedback real nos stories. Sem firula. Apenas a verdade nua e crua de que seu método funciona." },
        { day: 4, title: "POLARIZAÇÃO", task: "Faça um post 'Contra o Mercado'. Diga algo que todos concordam mas que está errado. Atraia inimigos para atrair fãs fanáticos." },
        { day: 5, title: "BASTIDORES FEIOS", task: "Mostre o trabalho duro. Não o café no coworking, mas a planilha, o estudo, o suor. Gere respeito, não inveja fútil." },
        { day: 6, title: "A OFERTA DIRETA", task: "Venda. Sem 'link na bio'. Diga 'Eu tenho X, Custa Y, Serve para Z. Quem quer, me chama'. Filtre os fracos." },
        { day: 7, title: "ANÁLISE DE DANOS", task: "Veja quem saiu e quem ficou. Quem ficou é sua tribo real. Comece a conversar com eles um a um." }
    ];

    const verdictColor = result?.verdict.includes('POSICIONAMENTO') ? 'text-red-500' :
        result?.verdict.includes('ALCANCE') ? 'text-yellow-500' : 'text-blue-500';

    return (
        <div className="min-h-screen p-4 md:p-8 max-w-4xl mx-auto pb-24">
            <header className="mb-12 border-b-2 border-white pb-6">
                <h2 className="text-xs font-mono text-gray-400">PLANO TÁTICO</h2>
                <h1 className="text-3xl md:text-5xl font-bold tracking-tighter uppercase">
                    PROTOCOLO: 7 DIAS
                </h1>
                <p className={`mt-2 font-mono text-sm ${verdictColor}`}>
                    FOCO: {result?.verdict || "RECONSTRUÇÃO TOTAL"}
                </p>
                <p className="mt-4 text-xs font-mono text-gray-600 flex items-center gap-2">
                    <span className="inline-block w-2 h-2 bg-green-500 rounded-full animate-pulse"></span>
                    Análise gerada por IA • Llama 3.3 70B
                </p>
            </header>

            <div className="space-y-6">
                {planDays.map((item) => (
                    <div key={item.day} className="border-2 border-dashed border-gray-700 p-4 md:p-6 hover:border-white transition-colors duration-300">
                        <div className="flex flex-col md:flex-row gap-4 md:items-start">
                            <div className="md:w-24 shrink-0">
                                <span className="text-4xl font-bold text-gray-800 font-mono">
                                    0{item.day}
                                </span>
                            </div>
                            <div>
                                <h3 className="text-xl font-bold uppercase text-white mb-2">{item.title}</h3>
                                <p className="font-mono text-sm text-gray-300 leading-relaxed">
                                    {item.task}
                                </p>
                            </div>
                        </div>
                    </div>
                ))}
            </div>

            <div className="mt-16 text-center space-y-6">
                <p className="font-mono text-xs text-red-500 uppercase tracking-widest">
                    ESTE PLANO SE AUTODESTRUIRÁ SE VOCÊ FOR FRACO.
                </p>
                <button
                    onClick={onReset}
                    className="brutal-btn w-full md:w-auto bg-white text-black hover:bg-red-600 hover:text-white border-none"
                >
                    ENCERRAR SESSÃO
                </button>
            </div>
        </div>
    );
};
